### ISSUE TITLE
Paging CSS at bottom of page is missing.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#1057]

**Comment by tpendragon** [comment]
Attaching screenshots appears broken.

**Comment by escowles** [comment]
What I'm seeing now on plum.princeton.edu (same locally and with Hyrax master):
![screen shot 2017-03-02 at 3 04 16 pm](https://cloud.githubusercontent.com/assets/856924/23524677/a0e93a4a-ff59-11e6-9929-57eda3490b39.png)

The "Previous" and "1" links go to the current page and have the `disabled` class, but are otherwise the same as the other links.  Do we want to gray them out? Actually disable them with javascript?

**Comment by jpstroop** [comment]
Either of this is fine w/ me.

**Comment by tpendragon** [comment]
Er, I assumed that this was using the bootstrap paging CSS and it just wasn't loading. Maybe I was wrong?
