### ISSUE TITLE
Too many scanned resources

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#1074]
@escowles will probably have an exact count, but the facet currently says 4336. I think migrated about half that. Could it be volumes within MVWs?

**Comment by jpstroop** [comment]
There's a lot of strange stuff at the end of the search results

https://plum.princeton.edu/catalog?f%5Bhuman_readable_type_sim%5D%5B%5D=Scanned+Resource&locale=en&page=432&q=

Maybe related

**Comment by tpendragon** [comment]
I think what happened here is a bunch of large MVWs got reindexed, which deleted the MVW but NOT the SRs attached to it.

**Comment by escowles** [comment]
I generated a list of SRs and their parent MVWs.  There are only 10 real MVWs, so I think the other parents are failed MVW ingests that have been deleted, leaving behind 3080 SRs that say they are a member of a MVW that doesn't exist any more.

But that still leaves nearly 4000 SRs, which seems like it too many.  I'm going to use this ticket to track the analysis and cleanup of these, and create a new ticket for deleting SRs when a MVW is deleted.

**Comment by escowles** [comment]
Based on the METS files in Google Drive, I think we should have:
* 2742 METS files
* 2597 standalone SRs
* 145 MVWs (containing 1234 volumes)
* a grand total of 3831 SRs (standalone + volumes)

There are currently 7527 SRs in Solr, so I think the 3080 SRs that I identified as being members of non-existent MVWs are probably failed ingests, and can be deleted.

**Comment by escowles** [comment]
After correctly removing all 169 MVWs, instead of just the first 10, I now have a list of 1609 SRs that are members of MVWs that don't exist.  I looked into checking the replaces field — but we're not setting that for the volumes in a MVW, so I don't think that will help us here.

**Comment by tpendragon** [comment]
So we're down to 2,655 SRs and 168 MVWs...maybe the rest are dups?

**Comment by tpendragon** [comment]
So running:
```
solr.get("select", params: {q: "*:*", rows: 1, facet: true, 'facet.field': 'identifier_ssim', 'facet.mincount': 2})
```

I get no duplicates (no two items have the same Ark)

Running
```
solr.get("select", params: {q: "*:*", rows: 1, facet: true, 'facet.field': 'source_metadata_identifier_ssim', 'facet.mincount': 2, 'facet.limit': -1})
```

I get seven bib-ids that have duplicates.

I don't know where all the others are from - maybe our METs count is wrong? Geo items? PULFA items?

**Comment by escowles** [comment]
If anything, I think the SR count is now a little lower than what I would expect — [earlier](https://github.com/pulibrary/plum/issues/1074#issuecomment-286122486) I counted the METS files and came up with 2597 PUDL SRs, and we've loaded about 170 PULFA SRs, so that adds up to about 2770.  I'm seeing 2655, so about 100 fewer.

I think we can close this ticket, since the big problem of having tons of extra SRs looks fixed to me (if I do an empty search and go to the end, I don't see any SRs that look like detached volumes).  But I think we still have work to do to get the last ~15 PUDL items to ingest, and validate that all the items ingested successfully).
