### ISSUE TITLE
Lapidus ARKs not in MARC records

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#1373]
We need a solution for getting ARKs into the catalog in general, but depending on how that works out, this may need to be done retrospectively. @escowles @tpendragon maybe you could discuss some of the ideas we were kicking around last week with @joycebcat?

**Comment by escowles** [comment]
@joycebcat, we talked about the process for adding ARKs to Voyager records, and IIRC, the options were either editing individual records, or downloading records, adding the ARKs, and then uploading the edited records to update them.

Since we store the metadata we pull from Bibdata, we can do a query to find records with ARKs that are not in the stored metadata.  One option we discussed was doing that query, retrieving the MARC for each record, and then downloading the MARCXML for all of the records with the ARKs from Plum added.  Would that let you bulk-update Voyager?  If so, that seems like the easiest way we have thought of to add many ARKs to Voyager.

**Comment by joycebcat** [comment]
Hi Esmé

I'm away until Thursday. I'll get back to you once I get back and catch up on things.

Joyce

On Jun 26, 2017, at 7:44 AM, Esmé Cowles <notifications@github.com<mailto:notifications@github.com>> wrote:


@joycebcat<https://github.com/joycebcat>, we talked about the process for adding ARKs to Voyager records, and IIRC, the options were either editing individual records, or downloading records, adding the ARKs, and then uploading the edited records to update them.

Since we store the metadata we pull from Bibdata, we can do a query to find records with ARKs that are not in the stored metadata. One option we discussed was doing that query, retrieving the MARC for each record, and then downloading the MARCXML for all of the records with the ARKs from Plum added. Would that let you bulk-update Voyager? If so, that seems like the easiest way we have thought of to add many ARKs to Voyager.

**Comment by escowles** [comment]
@joycebcat @mzelesky Bringing this back up.  I think it would be pretty easy for Plum to generate a report of ARKs in Plum records that are not in the corresponding Voyager records.  I'm not sure what options we have for bulk-adding those ARKs to the Voyager records.  So I'd appreciate any thoughts you have about what would make that process easier for you.

**Comment by mzelesky** [comment]
I have been working with @eliotjordan on bulk-adding ARKs. My process has been as follows:

1. Get list of Voyager bibIds with corresponding ARKs from http://lib-geoadmin.princeton.edu/images
2. Create hash out of them.
3. Export Voyager records.
4. Add in URLs into 856 fields.
5. Remove old URLs that are no longer needed (need some clarification from catalogers which URLs fall into that category).
6. Re-import files using Bulk Import.

**Comment by mzelesky** [comment]
The process has stalled because some data integrity issues were discovered in the Images DB used for finding the corresponding bib for a given ARK.

**Comment by escowles** [comment]
@mzelesky There are also other records that are being ingested by the studio, where we'd like to have the ARKs bulk-added to the Voyager records.  Right now, you can search for ARKs in Plum and the ARK and Bib ID are both shown in the search results.  It would be pretty easy to improve this process with a bulk-input form, or whatever would make the process easier for you.

**Comment by mzelesky** [comment]
A CSV with the ARKs and corresponding bib IDs would be easiest. I would be hesitant to put in place any process that bypasses manual intervention (i.e., a drop folder that auto-loads the records and adds the URL), due to the errors that were uncovered with the last load. While I wouldn't check every ARK to make sure it matches up with the bib in Voyager, I could search for ARKs that correspond to multiple bib IDs and bib IDs that have multiple ARKs. The most prominent example of these types of errors I know of is https://plum.princeton.edu/catalog?utf8=%E2%9C%93&q=9451937

If a report could be made of all ARKs in Plum with bib IDs where the corresponding Voyager record does not have the URL, that would greatly facilitate the process. 

I wouldn't want to use the MARCXML pulled from bibdata, as it alters the records (adding a 959, omitting any 852s that were in the original record, etc.). I would pull fresh copies of the Voyager records, add in the ARK using a script, then re-import the records. Voyager also cannot directly accept MARCXML.

**Comment by jpstroop** [comment]
That number seems really large.

**Comment by escowles** [comment]
@mzelesky and I talked about this, and we think it's possible that the issues with the map data are the main culprit here (there are 27,499 ImageWorks in Plum, for example).  I'm going to look at the duplicate Bib and ARK entries and figure out which types and collections these are coming from).

**Comment by joycebcat** [comment]
@escowles @mzelesky I suspected that the maps were probably the reason for the size of the number.  I have my own list of what I have/haven't ARKed up in the past.  I'd like to take a look at the list you provided for the non-map material and see what is in there.

I'm not exactly clear from the earlier messages whether we anticipate some automatic process going forward, but it kind of sounds like not?

**Comment by escowles** [comment]
@joycebcat Given the issues so far, I think we want to go with a more careful review before loading the ARKs into Voyager.  Once we resolve the data issues, it would be nice to have an automated process — but we want to avoid the kind of problems we had with the map data previously.

I'm working on a report right now that will separate the maps from the other materials in Plum.  Hopefully that will shed some light on the duplicate records and other problems Mark was describing.

**Comment by escowles** [comment]
After filtering by type, I see there are many fewer books (2,221), so it probably makes sense to stick with these for now.  I also see there are no duplicate ARKs and only three duplicate Bib IDs (two each for 8494555, 8529545, and 8544955).  Those items appear to all be Cicognara fiche items, where I believe we have multiple different digitized items that share the same Bib record (which has both of the items DCLNum ids in the 024 field).

[missing-arks-books.txt](https://github.com/pulibrary/plum/files/1229100/missing-arks-books.txt)

**Comment by joycebcat** [comment]
@escowles I got a slightly higher number by matching against Voyager and removing the ones coded as cartographic.  I'm looking into adding the ARKs for these 2,000+ objects myself.

**Comment by escowles** [comment]
@joycebcat Any update on adding ARKs for these items?

Also, there is a third set of objects that will have ARKs that need to be added to Voyager records: the Table of Contents  scanning project will be creating Plum objects with scans of the tables of contents for journal titles and monograph sets where there is no electronic content or indexing available.  These will be simpler than the other cases, since these will always be added 856 entries, so there won't be the same issue with possibly needing to update/replace old 856 fields.

**Comment by joycebcat** [comment]
@mzelesky Mark, when we were talking recently in your office, was this one of the things we talked about you doing?  I might be getting two different things mixed up in my head right now.
