### ISSUE TITLE
Warn if a Bib ID is already in use

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#207]
When I enter a Bib ID, query Solr to see if it's already been used for another resource, and display a warning if it is.

**Comment by escowles** [comment]
I thought we wouldn't need to have more than one record with the same bib id: you would either put it at the MVW or the SR level, but not both.  Is there a scenario were we'd want to have it at both levels?

If we can avoid having the same bib id at both levels, then we can have a validator that prevents using a bib id that's in use already.

If we do need to duplicate, we could have an AJAX call to check if the bib id is in use and provide visual feedback in the create/edit forms.

**Comment by jpstroop** [comment]
Another angle: There are a few scenarios where we've digitized multiple copies of the same title and we'd want to keep them as separate

**Comment by jpstroop** [comment]
But you're right, now that we've fleshed out MVWs I think we're OK for those. I could imagine something starting life as a single vol and then being added to an MVW later, but that wouldn't be a problem, right?

**Comment by escowles** [comment]
If you had a single volume, and then wanted to scan another volume, I'm guessing you'd want to update the metadata anyway.  So removing the bib id and work metadata from the original volume, and moving it to the new MVW would make sense.

But I take your point about digitizing multiple copies of the same title (esp. thinking of Cicognara), it might be better to just warn about the existence of other items with the same bib id, rather than completely preventing it.

**Comment by jpstroop** [comment]
> it might be better to just warn about the existence of other items with the same bib id, rather than completely preventing it

That's where my thoughts were leading too.
