### ISSUE TITLE
misplaced radio buttons in bulk editor

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#241]
In Chrome and FF on Linux, on FF for everyone(?) else:

![](https://cloud.githubusercontent.com/assets/999701/11641942/22c06cfa-9d09-11e5-9ee5-5d5bcee9e959.png)

**Comment by tpendragon** [comment]
This turned out to be much harder to fix than I expected. The problem is that the radio button is really 100% of the width, but the icon renders on the left in some Chromes, and center everywhere else. If you reduce the width of the button element, it works, but because jQuery UI Selectable takes over the click events and prevents event propagation, it stops the ability to click the labels and have the radio buttons selected.

I'm not sure what to do here.

**Comment by jpstroop** [comment]
Cop out and make it a dropdown?

**Comment by tpendragon** [comment]
Found the option in Selectable to ignore certain selectors.
