### ISSUE TITLE
Define descriptive metadata to display & edit

### ISSUE THREAD

**Issue by terrellt** [pulibrary/plum#32]
Define descriptive metadata fields to display along with the labels for each field.

Also declare which of these fields should be included in the form on the Edit page.  All others will only be populated from remote metadata.

**Comment by flyingzumwalt** [comment]
@jpstroop if you work on this tuesday morning, we should be able to set up the views that afternoon.

**Comment by jpstroop** [comment]
@terrellt @flyingzumwalt I won't get to this before the call on Tuesday as I won't be in the office until about 30 minutes before. This is something we'll need to refine over time and doesn't feel like a major priority to me at the moment (#46 seems more important). Let's just get something in place so that this isn't blocking. Go with title/creator/date.

Note that once we're creating IIIF Manifests for the books (#21) we _could_ use that to render the metadata labels/values on the  page.

**Comment by terrellt** [comment]
Related to https://github.com/projecthydra-labs/curation_concerns/issues/300

**Comment by terrellt** [comment]
Work to be done in #51
