### ISSUE TITLE
Does converting to JPEG improve OCR performance?

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#481]

**Comment by escowles** [comment]
I did some testing of OCR performance, comparing processing TIFFs directly, compared to various resolutions of JPEG.  I found that converting to JPEG makes processing slightly faster, and downsampling improves this further (even including the time to generate the JPEGs).  Times for processing 60 images (pudl0134/2084419):

* Original TIFFs: 1212 sec
* Full-res (5325x7200) JPEGs: 1052 sec
* 4800px JPEG: 701 sec
* 3600px JPEG: 576 sec
* 2400px JPEG: 484 sec
* 1200px JPEG: 472 sec

I haven't really compared the quality of the output yet, because the hocr is very hard to read.  But I'll work on making that readable in order to make some comparisons on what the performance/quality tradeoff looks like.

**Comment by jpstroop** [comment]
I wonder if converting to grayscale rather than scaling the size would make a difference?  @roelmoon, any thoughts?

**Comment by rmoon** [comment]
JPEG is definitely faster than TIFF, and text that stands out yields more accurate results than black text on brittle, yellowed paper (of course!). Optimized jpegs are ideal for OCR, but only if this change can be made efficiently. If you’re working from material like blue mountain, where we photographed to 7200 on the long side, then downsampling to 3600 is best (12” x 300 PPI). Items like LAE and brittle books are photographed at 400 PPI, so no resampling is necessary.

So the short answer is that a 300-400 PPI optimized (for text legibility) JPEG image will take the least amount of time to process and yield the highest OCR accuracy. In Imagemagick, increasing contrast 10 percent might be a starting point for a universal text-optimized image. Converting images to grayscale may help, but from the few tests I’ve done, an optimized grayscale and an optimized RGB file at the same resolution yields the same OCR accuracy. Also, because of the algorithm JPEG uses, these same files are nearly the same size when compressed.

**Comment by escowles** [comment]
I tried a couple of objects with these settings (300 dpi, grayscale JPEG, boosted contrast) and they were 30% and 50% faster.

I manually cleaned up the HOCR output for a random page to see if they were equivalent, and found only three differences (where the OCR from the JPEG was correct where the OCR from the TIFF was incorrect).

So I think these settings look very promising.
