### ISSUE TITLE
Loris should clear internal caches when source JP2s are updated

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#499]
When I replace an image:
- The JP2 derivative should be replaced
- The image server should clear any internal cache and generate images from the updated JP2

**Comment by escowles** [comment]
I just verified that Plum regenerates derivatives when a file is replaced.  Replacing a TIFF resulted in the JP2 and HOCR being replaced with new versions derived from the new TIFF.

I'm going to rename this ticket to be a placeholder for Loris gracefully handling updated JP2s and invalidating its internal caches.

**Comment by jpstroop** [comment]
I just had a look into this, and it's trivial to do w/ derivative images, but less so with the `info.json` (just because the code is in need of a serious refactor).

I've been thinking about pulling all of the caching out of Loris anyway and so can't get too excited about spending a ton of time on it. My thought it that users who want a cache can configure Varnish or Squid (the former seems _much_ easier). I wonder if someone wants to try that now--I think it's just a matter of:

 1. Disabling caching in `/etc/loris/loris2.conf`
 2. Change the port for Loris 
 3. Install and configure Varnish. The biggest questions I have are around SSL and whether we'd have to configure Apache to add any additional headers to get Varnish to work--I think we already have it adding an `Expires` header.

With Varnish in place, purging  from the cache [seems trivial](http://twigstechtips.blogspot.com/2014/04/varnish-enabling-wildcard-purging-of.html).

**Comment by jpstroop** [comment]
Temporary solution is to clear entire cache at regular intervals, which seems to be working fine for now.

**Comment by tpendragon** [comment]
@jpstroop Given that you're rethinking caching in Loris, do we want to keep this open or close it for now?
