### ISSUE TITLE
BagIt i/o

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#564]
@marvinmarvinb and I had a conversation with a vendor today about offsite backups, and it seems like being able to round trip our objects in a Fedora-independent way would probably be the best way to interact with this (or any other) backup service. Warrants further exploration anyway. Wonder if this is something we could get into CC or if it's more model specific.

**Comment by escowles** [comment]
I think this should be in CC: we would just need to start with an object and follow its member relationships, so I don't think there is anything model-specific there.  This seems like a good background job to add to the existing CC stable of background jobs.

**Comment by tpendragon** [comment]
Oh, hey, I've done this one before. We'd have to update (read rewrite) the BagIt ruby library, but :+1: to it being an export format in CC.

**Comment by jpstroop** [comment]
(admits to leading @tpendragon) HyBag was a thing somewhere at some point, right?

export AND import, right?

**Comment by tpendragon** [comment]
Yeah. Really we should write up the crosswalk from Works to Bags, since bagit doesn't really concern itself with hierarchy. 

Hybag: https://github.com/projecthydra-labs/hybag for FCR3 though. I know Oregon has some tickets in their upcoming sprints to fix it all up for Fedora 4.

**Comment by jpstroop** [comment]
@kestlund is interested as well.

**Comment by tpendragon** [comment]
In thinking on this, ingest will be the hard part because of referential integrity constraints in Fedora 4. Means you have to start ingesting from the leaf nodes, which means you have to find them first.

**Comment by escowles** [comment]
I agree that ingest will be complicated by having to ingest stuff before you can refer to it.  So that kind of winds up looking like the METS ingest, where you need to ingest files and maintain an identifier mapping so the higher levels can refer to them correctly.

**Comment by jpstroop** [comment]
FWIW, I thinking about this more in terms of a restore format than regular ingest format. If we can't restore from it, it's definitely not a good backup format! :smile:

**Comment by escowles** [comment]
I agree that you want to be able to restore an object more easily than re-ingesting it.  Assuming you're using NOIDs and not Fedora's builtin identifier generation, then you could avoid having to do identifier translation.  So you pretty much just need to order things so that you're creating FileSets before the objects that link to them, etc.  I don't know what the current status is, but I think people are working on Fedora tooling to restore files and RDF from disk.  So the restore functionality we'd need would be to look at the objects in a Bag, figure out how they link to each other, and then use the restore them in the right order so the references work out.

**Comment by tpendragon** [comment]
For sure. Mostly just leaving notes here so I remember what I was thinking when we start developing the feature. 

I wonder if we can export leaf-first, and if that would make things easier. Also wonder what export of a MVW even looks like. A bag of zipped bags?

**Comment by escowles** [comment]
MVWs are an interesting case.  Because I can see wanting to export the member ScannedResources separately.  So maybe we wouldn't bundle the members at all, and just assume they'll be backed up separately?

**Comment by jpstroop** [comment]
Just to be clear, it doesn't have to be bags, but the vendor we were talking to yesterday understands them and knows how to validate them, etc., and that seems like a fairly typical case. Plus it's a nice, hardware/software independent community standard. If we can use it, great, if something based on, e.g. METS is better, that's fine too, but I think we'd get more community buyin from BagIt

**Comment by kestlund** [comment]
The argument for bags is especially strong for us, because so many of the
third party community archival platforms want some form of bag or bag-like
structure for MetaArchive, APTrust, NDNP data at LC etc. I don't only want
to restore from Fedora, but I want to transfer to those platforms, then
restore from those dark places.

I do have my separate use case wish for a migration of bags from a certain
propriety system, but that is perhaps a separate issue.

**Comment by jpstroop** [comment]
> [...] so many of the third party community archival platforms want some form of bag or bag-like
structure for MetaArchive, APTrust, NDNP data at LC etc. I don't only want
to restore from Fedora, but I want to transfer to those platforms, then
restore from those dark places.

We're on the same page. I'm want about restore _to_ Fedora/Hydra as well, _from_ an understood structure (like a bag if not a Bag) that we've stashed somewhere (e.g.  Duracloud, Arkivum).
