### ISSUE TITLE
Multiple titles should go in separate H1 tags on object show pages, so RTL scripts can be displayed RTL

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/plum#599]
Once you are select an object from a result list to view, the non-roman script title displays above the image viewer, but the Romanized titles doesn't show up anywhere on the page.

**Comment by escowles** [comment]
I believe this was fixed by the recent updates — I'm seeing both the native script and romanized versions of the title at the top of the page now, e.g.: https://hydra-dev.princeton.edu/concern/scanned_resources/rv042t299 and https://hydra-dev.princeton.edu/concern/scanned_resources/9p290952r .

@joycebcat, please re-open if there are records where this is still a problem.

**Comment by tpendragon** [comment]
Commas aren't really appropriate, yeah?

**Comment by escowles** [comment]
A `<br/>` tag would probably be better, like we're doing on the search results page.

**Comment by tpendragon** [comment]
I was going to do separate H1 tags so we could do RTL.

**Comment by escowles** [comment]
Separate H1 tags would be better — I'll update the title of the ticket.
