### ISSUE TITLE
Individual volumes of multi-vol works showing in search results

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#766]
E.g.: http://lib-plum1.princeton.edu/catalog?f%5Bgeneric_type_sim%5D%5B%5D=Work&works=mine

![image](https://cloud.githubusercontent.com/assets/999701/19433278/f764a78e-942d-11e6-8308-8f2c3c10faed.png)

**Comment by escowles** [comment]
I think those are all volumes that failed to ingest completely.  So the ScannedResource was created and some pages were added, but the error failed to associate it with the parent MultiVolumeWork (which is why they show up in the search results).

So I think making the ingest more reliable will fix this, though we could also update the volume ingest code to link the ScannedResource to the MVW before ingesting pages.
