### ISSUE TITLE
Sort by ____ not working

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#932]
This:

![image](https://cloud.githubusercontent.com/assets/999701/21702417/38604b46-d379-11e6-90be-6c474c54c8fd.png)

Seems to be the same no matter what, at least w/ dates

**Comment by escowles** [comment]
I think sorting is mostly working, with some quirks.  In particular, sorting by modification date doesn't seem to work because basically nothing has been modified.  I just added a workflow note to a resource (https://plum.princeton.edu/concern/scanned_resources/p8623jw50m) and now it sorts by modification date as expected.

**Comment by jpstroop** [comment]
Sorting by date uploaded ascending and descending return the same results for me.

**Comment by escowles** [comment]
Sorting by date uploaded works for me locally, but not in production.  Maybe there's an issue with the ingested works instead of manually-created objects?
