### ISSUE TITLE
Reconsider flagging

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#940]
With Sipity, it's not clear if we can easily have any logged-in user able to flag resources.

Discussing this led us to wonder whether it still made sense to have end users flagging resources in Plum.  If they are viewing the resource in OL or Pom, maybe it makes more sense to have some other way to report resources that need attention though those apps?

**Comment by jpstroop** [comment]
Could probably switch to ServiceNow or a feedback listserv if that's easier. I'm down on listservs at the moment because you can assign work or see if someone has taken care of it, so maybe we should see if we can bend SN@P to actually be useful? Or...the tech services is using something else. Might be worth finding out what that is.

**Comment by tpendragon** [comment]
Basically the question here is "does the public ever see Plum", and if it's "no", then we don't need public permissions.

**Comment by tpendragon** [comment]
I think as long as the ARK points at OL then :+1: to removing flagging.
