### ISSUE TITLE
Unflagged action needs description/badge

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#945]

**Comment by escowles** [comment]
![unflag](https://cloud.githubusercontent.com/assets/856924/21862560/bb570386-d807-11e6-994c-02e2178d3792.png)

**Comment by eliotjordan** [comment]
The unflag action is removed in the most recent iteration of the workflow. Instead of unflag, the user is simply offered the `Complete` action. Which transitions to 'complete' state. Same with `Takedown`. We could re-add the `Unflag` action, but then we should probably do the same for the whatever the opposite of takedown is called. `Remove Takedown`? Complete just seems simpler.

https://github.com/pulibrary/plum/blob/325c563e538ee02adc5794beaa6b61e4d9735d7a/config/workflows/geo_workflow.json#L57-L60

**Comment by escowles** [comment]
👍  to just having Complete as the action available for Takedown and Flagged.
