### ISSUE TITLE
Supressed Voyager records

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#959]
@joycebcat These are failing to migrate because the Voyager records are suppressed.

```
pudl0058/9689855
pudl0079/9623172
pudl0079/9623174
pudl0079/9623176
pudl0079/9623177
pudl0079/9623179
pudl0079/9623180
pudl0123/8491349
pudl0127/4768260
pudl0127/4746986
pudl0127/4764418
pudl0127/4842210
pudl0127/4757753
pudl0127/4764993
pudl0127/4764517
```

**Comment by jpstroop** [comment]
I notice that the MODS have some different `accessConditions`. It should be possible to copy those into Plum, though for this small number it's probably easiest to just do that manually.

**Comment by joycebcat** [comment]
@jpstroop Augh!  I need to share my pain.  It seems for some of these at least, Cotsen staff deleted the earlier records and then created new ones so all the bib numbers have changed.

pudl0058/9689855 -- I can't unsuppress this because it has no holdings (will have to ask RB to finish record)

These have no bib record.  I don't know where you got the V id from.  The file names don't use V bib ids, and I searched and couldn't find the numbers inside any of the mods records as referents to V:
pudl0079/9623172
pudl0079/9623174
pudl0079/9623176
pudl0079/9623177
pudl0079/9623179
pudl0079/9623180

The bib record below doesn't exist either.  The real number is 9647940:  
pudl0123/8491349

These are the Cotsen specials, except for the one with the encoding problem as noted below:
pudl0127/4768260 -- new bib record 9954751 
pudl0127/4746986 -- this is the one you wrote about with the potential bad encoding in 245
pudl0127/4764418 -- new bib record 9953665 
pudl0127/4842210 -- new bib record 9953942 
pudl0127/4757753 -- new bib record 9961805 
pudl0127/4764993 -- new bib record 9986094 
pudl0127/4764517 -- new bib record 9959845

**Comment by jpstroop** [comment]
Wow OK.

> pudl0058/9689855 -- I can't unsuppress this because it has no holdings (will have to ask RB to finish record)

Do you want to ask Don? Or should I take it over? They recently worked to unsupress everything in pudl0058 (~200 records I think) so I suspect this one was just missed.

> pudl0079/9623172
> pudl0079/9623174
> pudl0079/9623176
> pudl0079/9623177
> pudl0079/9623179
> pudl0079/9623180

These numbers are in the [MODS `recordOrigin`](http://diglibsvn.princeton.edu/svn/puldi/pudl/branches/development/mdata/pudl0079/glaser079.mods). Any chance they can at least be stubbed? Otherwise I'd rather leave all of Yemeni in the PUDL for now.

For the rest, I think we can update the metadata and try again. I'll get going on that now.

**Comment by joycebcat** [comment]
I just went ahead and unsuppressed the RB record after adding a placeholder holdings.  

The problem with the pudl0079 records is that I had no idea what titles are involved.  You gave me a number, I can't find that number in V or in any of the mods or mets records.  I don't know what they are so I can't match them to a V record.

**Comment by jpstroop** [comment]
For 79, I think it's all of the glaser records, e.g: 
http://diglibsvn.princeton.edu/svn/puldi/pudl/branches/development/mdata/pudl0079/glaser079.mods

**Comment by jpstroop** [comment]
Also, (sorry!) I found two more for pudl0127: `4746986`, `4758329`

**Comment by jpstroop** [comment]
And one more: `4764474` ...

**Comment by jpstroop** [comment]
@joycebcat - just checking that you saw the three additional items from pudl0127 that I found later:
`4746986`, `475832`, `4764474`

**Comment by joycebcat** [comment]
@jpstroop Yes,  4746986 I unsuppressed last week.  475832 is a 1986 publication we wouldn't have digitized and it isn't suppressed so something is wrong there.   4764474  doesn't exist in Voyager. 

The pudl0079 objects which you thought were Glaser, aren't.  The Glaser bib records have ids beginning with 7848-

**Comment by jpstroop** [comment]
OK, thanks.

I lopped a number off of "475832" - should be "4758329". This and 4764474 are more of the Russian children's lit. that Cotsen recataloged, so we probably just need a correct number. 

Re: Glaser, or whatever they are, these six:

glaser198.mods
glaser111.mods
glaser079.mods
glaser147.mods
glaser217.mods
glaser073.mods

Point to BBIDs that are either suppressed or don't exist.

**Comment by joycebcat** [comment]
OK, below are all the current bib ids for the remainder of the objects in the messages above.

glaser198.mods = 7848955 
 glaser111.mods = 7848933 
 glaser079.mods = 7848926 
 glaser147.mods = 7848954 
 glaser217.mods = 7848960 
 glaser073.mods = 7848922 

4758329 = 9997598 
4764474 = 9953586

**Comment by jpstroop** [comment]
Thanks!
